### ISSUE TITLE
Error Selecting data from registry$

### ISSUE THREAD

**Issue by iczcrash** [lschilde/Sharing_APEX_SERT_24_1#3]
At first, thank you for your massive effort to provide this tool for free!
Just a minor thing, I will just ping you what I am experiencing.

Running ins.sql on the wrong APEX version leads to this console output:

```
...... Test for Oracle 11.2.0.4 or above
...... Test for XE Edition of Oracle
...... Test for Valid Instance of APEX 5.1.0 or above
Error Selecting data from registry$
ORA-01722: invalid number
declare
*
ERROR at line 1:
ORA-00900: invalid SQL statement
ORA-06512: at line 17
ORA-01722: invalid number
ORA-06512: at line 6
```

**Comment by lschilde** [comment]
this is related to this line.. are you running this as sys user or? select to_number(replace(version,'.',null)), status from registry$ where cid='APEX'

**Comment by iczcrash** [comment]
I was running this as sys.
It's just a UX issue I would say.
The scrips is expecting that the query is returning a row.

**Comment by lschilde** [comment]
Yes and I think it should return a row let me double check this...

**Comment by lschilde** [comment]
You can try running this with changing line 188 in ins_auto_setup.sql make l_version a varchar2(100) vs the number as it currently is.

**Comment by lschilde** [comment]
In ins.sql that should be line 166.

**Comment by lschilde** [comment]
see if that does it

**Comment by lschilde** [comment]
I still can not find why it would fail with this error 

This is what I am getting 

`SQL> select con_id,version_full,to_number(replace(version,'.',null)), status from cdb_registry where comp_id='APEX';    

CON_ID VERSION_FULL                   TO_NUMBER(REPLACE(VERSION,'.',NULL)) STATUS
---------- ------------------------------ ------------------------------------ -----------
         3 21.1.0                                                         2110 VALID
         5 22.1.0                                                         2210 VALID
         4 24.1.3                                                         2413 VALID
         6 23.2.0                                                         2320 VALID


cdb19a> select con_id,version_full,to_number(replace(version,'.',null)), status from cdb_registry where comp_id='APEX';    

CON_ID VERSION_FULL                   TO_NUMBER(REPLACE(VERSION,'.',NULL)) STATUS
---------- ------------------------------ ------------------------------------ --------------------------------------------
         3 22.2.14                                                       22214 VALID
         4 18.2.0.00.12                                               18200012 VALID
         5 18.2.0.00.12                                               18200012 VALID`

**Comment by lschilde** [comment]
haven't heard back since so closing
