### ISSUE TITLE
ins_auto_setup.sql asks for value for 1

### ISSUE THREAD

**Issue by iczcrash** [lschilde/Sharing_APEX_SERT_24_1#4]
When I run sert_240100/ins_auto_setup.sql I will just see this:

Enter value for 1:

**Comment by lschilde** [comment]
Typically this means that it is accepting special substitution strings. try doing `set define off;` first

There is a comment in there how you run this usually.

`@ins_auto_setup.sql oracle oracle oracle lschilde@gmail.com USERS TEMP yes Y`

**Comment by iczcrash** [comment]
Thanks! Sorry, I am new to APEX-SERT, is there a documentation or should I read the sql scripts?

**Comment by lschilde** [comment]
You can find all documentation under the old repo https://github.com/OraOpenSource/apex-sert/tree/master/doc

**Comment by lschilde** [comment]
but auto_install script is a new script that I have added to make things faster. Its like a wrapper for ins.sql script :) Have a look at it it is simple as it can be it has comments all over.

**Comment by iczcrash** [comment]
Thanks 😄
