### ISSUE TITLE
need to replace connection string in ins.sql

### ISSUE THREAD

**Issue by iczcrash** [lschilde/Sharing_APEX_SERT_24_1#6]
For a successful login it was necessary for me to replace the connect string with fixed values in line 520 after the following prompt:
`PROMPT connect as SV_SERT_LAUNCHER for SERT Launcher Web Service part 2
`
I have also replaced the connect string after, in line 525.

Not sure what's happening here, perhaps an undefine is executed before.

**Comment by lschilde** [comment]
One to keep track of. Always revisit installation script before running it as different environments require slightly different settings
